### ISSUE TITLE
“最近收到的回复”对齐问题

### ISSUE THREAD

**Issue by if1y** [ouyangyanhuo/AdminMD#1]
后台首页右下方，“最近收到的回复”部分，我这边试用的结果是内容右对齐，导致内容比较短的评论回复就会和左边的日期间隔出一大截，很奇怪。

**Comment by ouyangyanhuo** [comment]
抱歉，一直忘了回复，麻烦可以提供截图吗

**Comment by if1y** [comment]
已经不再使用了，非常抱歉不便提供……
