### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by LovesAsuna** [ouyangyanhuo/AdminMD#14]
顶部出现Warning: Undefined array key 1 in /usr/share/nginx/typecho/usr/plugins/AdminMD/Plugin.php on line 189
然后没有效果

**Comment by ouyangyanhuo** [comment]
很抱歉现在才回复您的Issues，AdminMD已经进入开发瓶颈，未来可能不会保持更新，重构目前仍无进展。
不管你是否还在使用AdminMD这个插件，我还是要回答你，虽然可能会没有什么有价值的回答。
针对你所提出的问题，在实际测试中，无法复现，因此没有办法找到具体的原因。
1.请检查所使用的php版本，推荐使用php7.4
2.请检查您的nginx的配置情况
3.是否有其它插件与AdminMD冲突
4.是否替换了 ``Meun.php``，[wiki](https://github.com/ouyangyanhuo/AdminMD/wiki/Theme's-menu-does-not-take-effect)
AdminMD在使用了插件方法实现后，会出现许多未知的、不可复现的Bug，请见谅，Version1.5（老旧版本）会少许多问题，但是它使用的是覆盖Admin目录的方式，而不是插件实现。

**Comment by zsdili** [comment]
> 

切换PHP版本试试
