### ISSUE TITLE
handsome主题兼容性问题

### ISSUE THREAD

**Issue by LovesAsuna** [ouyangyanhuo/AdminMD#2]
头部出现白色边框
![4QR~%P3P$FW4YBT7WFI7JXT](https://user-images.githubusercontent.com/32810896/112475881-4404f900-8dac-11eb-9035-04da0a8fb524.png)
并且无法点击具体设置
![(3%9V $Z1BO P%_}J@C(DN5](https://user-images.githubusercontent.com/32810896/112475908-4bc49d80-8dac-11eb-9a65-29981bda8c4e.png) (具体表现为点开后缩回)

**Comment by ouyangyanhuo** [comment]
感谢支持，会尽力修复此Bug，目前处于暂停更新状态，预计七月份会恢复更新，很抱歉为您带来不便，您可以选择暂时不使用该后台模板。

**Comment by Lickoo233** [comment]
![YAU _RNW_D{L~_VUAP}~Z@T](https://user-images.githubusercontent.com/59186224/119167518-85efaa00-ba92-11eb-81c6-19e49239ffdb.png)
把所有文件复制进入admin文件夹之后变成白页，无法加载。我已经把所有插件都下了，也不行。目前在用的主题是Material主题，也是MDUI风格的。难道是和主题冲突了么？不应该呀。

**Comment by ouyangyanhuo** [comment]
> ![YAU _RNW_D{L~_VUAP}~Z@T](https://user-images.githubusercontent.com/59186224/119167518-85efaa00-ba92-11eb-81c6-19e49239ffdb.png)
> 把所有文件复制进入admin文件夹之后变成白页，无法加载。我已经把所有插件都下了，也不行。目前在用的主题是Material主题，也是MDUI风格的。难道是和主题冲突了么？不应该呀。
Duplicate of #

目前AdminMD对后台是覆盖式的更改，和任何可以对后台进行修改的主题都不兼容，目前正在开发升级插件版本，兼容性待新版本提高。
