### ISSUE TITLE
font-awesome.css的cdn引用失效

### ISSUE THREAD

**Issue by little-gt** [ouyangyanhuo/AdminMD#4]
在header.php的第26行的引用链接 “https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.css” 失效

```html
<link rel="stylesheet" href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.css">
```

建议换成cloudflare的 “https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css” CDN源
即换成：

```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
```

**Comment by ouyangyanhuo** [comment]
好的！

**Comment by ouyangyanhuo** [comment]
经过排查，近两个版本都没有上述内容，建议您手动替换，或者更新此插件
